apiVersion: v1
kind: Service
metadata:
  name: aws-rds
  namespace: salon-booking
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: aws-rds
  namespace: salon-booking
subsets:
  - addresses:
      - ip: 51.21.114.88 # AWS RDS IP address
    ports:
      - port: 3306
