apiVersion: v1
kind: Service
metadata:
  name: aws-rds
  namespace: salon-booking
spec:
  type: ExternalName
  externalName: database-1.cn8e0eyq896c.eu-north-1.rds.amazonaws.com  # REPLACE with your actual RDS endpoint
  ports:
    - port: 3306
      protocol: TCP
